name: Lint Checks
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Install Prototool
        run: python install_prototool.py
      - name: Run Lint Checks
        run: python pre_commit_linter.py --path=.
